[build]
  command = "npm run build" # Commande de construction de votre application Astro
  publish = "dist" # Dossier de distribution après la construction

[[headers]]
  for = "/assets/*" # Spécifiez le chemin des images dans votre application
    [headers.values]
      Cache-Control = "public, max-age=31536000" # Configuration de la mise en cache des images

[[redirects]]
  from = "/assets/*" # Redirigez les requêtes vers les images vers le bon emplacement
  to = "/assets/:splat"
  status = 200
